defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
name: Bluecology blog
description: Thoughts on science, ecology and Rstats
url: http://www.seascapemodels.org/index.html
